### ISSUE TITLE
Problems with new ID format of sacred 0.7b2

### ISSUE THREAD

**Issue by Qwlouse** [chovanecm/sacredboard#18]
Hi, 

I've changed the `_id` field in the new version of sacred form `ObjectId` to `int`. Unfortunately that breaks your current webapp:
``` 
Traceback (most recent call last):
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/greff/Programming/sacredboard/sacredboard/app/config/routes.py", line 53, in api_run
    runs = data.get_run(run_id)
  File "/home/greff/Programming/sacredboard/sacredboard/app/data/mongodb.py", line 26, in get_run
    cursor = self._db.runs.find({"_id": bson.ObjectId(run_id)})
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/home/greff/venv/sacredboard/lib/python3.4/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
bson.errors.InvalidId: '1' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```

**Comment by chovanecm** [comment]
Check it now, please. I noticed the problem when I wanted to run sacred0.7 beta with my existing database from sacred 0.6, it didn't work. Anyway I have already fixed it in sacredboard. It should work with both now.
Please reopen the issue if not.
