### ISSUE TITLE
invalid syntax error on running on Mac

### ISSUE THREAD

**Issue by evolu8** [chovanecm/sacredboard#89]
$ sacredboard
Traceback (most recent call last):
  File "/usr/local/bin/sacredboard", line 7, in <module>
    from sacredboard.bootstrap import run
  File "/Library/Python/2.7/site-packages/sacredboard/__init__.py", line 3, in <module>
    from sacredboard import bootstrap
  File "/Library/Python/2.7/site-packages/sacredboard/bootstrap.py", line 105
    "for more information.", file=sys.stderr)
                                 ^
SyntaxError: invalid syntax

**Comment by chovanecm** [comment]
Hi,
which version please?

**Comment by evolu8** [comment]
Python upgrade solved this. Sorry for the false alarm. And thanks for the quick response.
