### ISSUE TITLE
Invalid syntax error when running on Mac

### ISSUE THREAD

**Issue by wu9tiger** [chovanecm/sacredboard#99]
It is identical error for issue #89. But I couldn't get it to work. Python is already latest at 2.7.15 and sacredboard is also latest at 0.4.0

#sacredboard
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/sacredboard", line 11, in <module>
    load_entry_point('sacredboard==0.4.0', 'console_scripts', 'sacredboard')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sacredboard/__init__.py", line 3, in <module>
    from sacredboard import bootstrap
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sacredboard/bootstrap.py", line 105
    "for more information.", file=sys.stderr)
                                 ^
SyntaxError: invalid syntax

**Comment by chovanecm** [comment]
Hi, thank you for providing the log and information.
Python 2.7 is very old (8 years now) and not supported by Sacredboard.
Sacredboard has been tested with Python 3.5 and Python 3.6 (but I guess it should work with 3.7 too)
